(custom-set-variables
 '(message-log-max 250)
 '(sort-fold-case t t)
 '(recentf-max-menu-items 20)
 '(next-line-add-newlines nil)
 '(default-input-method "latin-2-prefix")
 '(save-place t nil (saveplace))
 '(uniquify-buffer-name-style (quote forward))
 '(auto-compression-mode t nil (jka-compr))
 '(ps-bottom-margin 72)
 '(case-fold-search t)
 '(show-paren-mode t nil (paren))
 '(recentf-exclude (quote ("/tmp/mutt")))
 '(desktop-buffers-not-to-save "(^nn.a[0-9]+\\|.log\\|(ftp)\\|^tags\\|^TAGS|^mutt-charlesc\\)$")
 '(current-language-environment "Latin-2"))
(custom-set-faces)
